

name: Streamlit App CI


on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      # 1. Checks-out repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Sets up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Cache dependencies to speed up subsequent runs
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip 
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }} 
          restore-keys: |
            ${{ runner.os }}-pip- 

      # 4. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Install packages listed in requirements.txt

      